### ISSUE TITLE
Event need 2 clicks to work instead of only 1 the first time

### ISSUE THREAD

**Issue by Velorum6** [dfdao/dfdao.github.io#11]
When you join the page, and you go to the DFDAO Adventures section, and click one of the events, you need to click 2 times the first time to make the description appear, not sure what is the problem.

**Comment by Bulmenisaurus** [comment]
maybe you should try to use `window.getComputedStyle(imageRemembered).display` instead of `imageRemembered.style.display`?

**Comment by Velorum6** [comment]
tried, but it doesn't work :S
