### ISSUE TITLE
Remove box outline for planet gallery

### ISSUE THREAD

**Issue by cha0sg0d** [dfdao/dfdao.github.io#14]
<img width="658" alt="Screen Shot 2022-03-16 at 4 47 14 PM" src="https://user-images.githubusercontent.com/42984734/158709592-9a339c9a-6b03-469c-b840-f271dee46bd5.png">

In my opinion, we should consider no outline on these planets and see if it looks good.

Also, I think we should only list planets that we have, the empty boxes look a bit odd

**Comment by Velorum6** [comment]
![image](https://user-images.githubusercontent.com/88809256/158712449-7d502467-5c38-4323-aacf-4de1fec84fe8.png)

this is how it looks like without borders, I don't really like it, maybe a good idea would be just remove the border of the big box that cointains all the smaller boxes and just make a separation between the planets a line

also about the empty boxes -> in the og design there was included some artifacts, but I don't have the artifact data to include them, if we can find it we could add them there, for example the Mythic planetary shield that dfdao bought

**Comment by Velorum6** [comment]
this looks better?
![image](https://user-images.githubusercontent.com/88809256/158712947-15cab52e-f575-4586-890a-b1d4eee78d19.png)

**Comment by cha0sg0d** [comment]
yeah I like that.

For artifacts, I think we'd need to copy over the in-game renderer from Dark Forest. They don't have official metadata.

**Comment by Velorum6** [comment]
Border changes merged, gonna close this issue and open another one about the artifact metadata,
